#include "License.h"
#include <QJsonObject>
#include <QJsonDocument>
#include <QFile>
#include <QByteArray>

#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/err.h>
#include <openssl/bio.h>
#include <openssl/buffer.h>

#include <ctime>
#include <cstdio>
#include <vector>


#define ENCRYPTED_STRING(x) EncryptedConstant::decrypt_string(EncryptedConstant::encrypt_string(x))

namespace LicenseManager
{
	// All key material is handled through the modern OpenSSL EVP interface. RSA
	// keys are still read/written as PEM so keys generated by older versions of
	// this library remain loadable, and the produced signatures are byte-identical
	// PKCS#1 v1.5 over SHA-256 (compatible with the previous RSA_sign path).
	static void print_openssl_error();
	static EVP_PKEY* generate_RSA_keypair();
	static std::string private_key_to_string(EVP_PKEY* private_key);
	static std::string public_key_to_string(EVP_PKEY* key);
	static EVP_PKEY* load_private_key_from_string(const std::string& private_key_str);
	static EVP_PKEY* load_public_key_from_string(const std::string& public_key_str);
	static std::string sign_message(EVP_PKEY* private_key, const std::string& message);
	static bool verify_signature(EVP_PKEY* public_key, const std::string& message, const std::string& signature);
	static std::string base64_encode(const std::string& binary_data);
	static std::string base64_decode(const std::string& base64_data);
	static std::string signature_to_string(const std::string& signature);
	static std::string string_to_signature(const std::string& base64_signature);
	static std::string sha256_hex(const std::string& data);
	static std::string current_iso_datetime();
	static std::string normalize_iso(const std::string& iso);

	
	const License::DecryptedStrings& License::decryptedStrings()
	{
		static License::DecryptedStrings decryptedStrings;
		static bool initialized = false;
		if (!initialized)
		{
			decryptedStrings.decrypt();
			initialized = true;
		}
		return decryptedStrings;
	}

	License::License()
	{
		class Initializer
		{
			public:
			Initializer()
			{
				// Initialize OpenSSL
				OpenSSL_add_all_algorithms();
				ERR_load_crypto_strings();
			}
			~Initializer()
			{
				// Cleanup OpenSSL
				EVP_cleanup();
				ERR_free_strings();
			}
		};
		static Initializer init;

	}
	License::License(const License& other)
	{
		this->operator=(other);
	}

	License::~License()
	{

	}

	License& License::operator=(const License& other)
	{
		m_signature = other.m_signature;
		m_licenseData = other.m_licenseData;
		m_name = other.m_name;
		m_hardwareId = other.m_hardwareId;
		m_validFrom = other.m_validFrom;
		m_validUntil = other.m_validUntil;
		return *this;
	}
	bool License::operator==(const License& other) const
	{
		if(m_signature != other.m_signature)
			return false;
		if(m_licenseData != other.m_licenseData)
			return false;
		if(m_name != other.m_name)
			return false;
		if(m_hardwareId != other.m_hardwareId)
			return false;
		if(m_validFrom != other.m_validFrom)
			return false;
		if(m_validUntil != other.m_validUntil)
			return false;
		return true;
	}
	bool License::operator!=(const License& other) const
	{
		return !this->operator==(other);
	}


	bool License::saveToFile(const std::string& filePath) const
	{
		if (m_nameChangedSinceLastSave)
		{
			// Remove file if name has changed
			QFile file(m_loadedPath.c_str());
			if (file.exists())
			{
				file.remove();
			}
		}

		QJsonObject json;

		// Additional info about this library
		QJsonObject libInfo;
		libInfo[decryptedStrings().jsonKeys.version.c_str()] = LibraryInfo::version.toString().c_str();
		
		QJsonObject licenseData;
		for (auto it = m_licenseData.begin(); it != m_licenseData.end(); ++it)
		{
			licenseData[it->first.c_str()] = it->second.c_str();
		}
		json[decryptedStrings().jsonKeys.licenseData.c_str()] = licenseData;
		json[decryptedStrings().jsonKeys.signature.c_str()] = m_signature.c_str();
		json[decryptedStrings().jsonKeys.libraryInfo.c_str()] = libInfo;
		json[decryptedStrings().jsonKeys.name.c_str()] = m_name.c_str();
		json[decryptedStrings().jsonKeys.hardwareId.c_str()] = m_hardwareId.c_str();
		json[decryptedStrings().jsonKeys.validFrom.c_str()] = m_validFrom.c_str();
		json[decryptedStrings().jsonKeys.validUntil.c_str()] = m_validUntil.c_str();


		QJsonDocument doc(json);
		QByteArray data = doc.toJson();

		QFile file(filePath.c_str());
		if(file.open(QIODevice::WriteOnly))
		{
			file.write(data);
			file.close();
			return true;
		}
		return false;
	}
	bool License::loadFromFile(const std::string& filePath)
	{
		QFile file(filePath.c_str());
		if(file.open(QIODevice::ReadOnly))
		{
			QByteArray data = file.readAll();
			QJsonDocument doc = QJsonDocument::fromJson(data);
			QJsonObject json = doc.object();

			m_licenseData.clear();
			QJsonObject licenseDataJson = json[decryptedStrings().jsonKeys.licenseData.c_str()].toObject();
			for(auto it = licenseDataJson.begin(); it != licenseDataJson.end(); ++it)
			{
				m_licenseData[it.key().toStdString()] = it.value().toString().toStdString();
			}
			m_signature = json[decryptedStrings().jsonKeys.signature.c_str()].toString().toStdString();
			m_name = json[decryptedStrings().jsonKeys.name.c_str()].toString().toStdString();
			m_hardwareId = json[decryptedStrings().jsonKeys.hardwareId.c_str()].toString().toStdString();
			m_validFrom = json[decryptedStrings().jsonKeys.validFrom.c_str()].toString().toStdString();
			m_validUntil = json[decryptedStrings().jsonKeys.validUntil.c_str()].toString().toStdString();
			file.close();
			m_nameChangedSinceLastSave = false;
			m_loadedPath = filePath;
			return true;
		}
		return false;
	}
	bool License::isVerified(const std::string& publicKey) const
	{
		EVP_PKEY* pubKey = load_public_key_from_string(publicKey);
		if(!pubKey)
			return false;
		std::string dataString = getDataString();
		bool isVerified = verify_signature(pubKey, dataString, m_signature);
		EVP_PKEY_free(pubKey);
		return isVerified;
	}

	License::VerificationResult License::check(const std::string& publicKey,
											   const std::string& currentHardwareId,
											   const std::string& nowIso) const
	{
		// 1) Signature must match the whole signed payload first. Everything else
		//    is only meaningful once we trust the data.
		if (!isVerified(publicKey))
			return VerificationResult::invalidSignature;

		// 2) Node-lock: if the license is bound to a machine it must match the one
		//    we are running on. Fail closed when no fingerprint was supplied.
		if (isNodeLocked())
		{
			if (currentHardwareId.empty() || currentHardwareId != m_hardwareId)
				return VerificationResult::wrongMachine;
		}

		// 3) Validity window. Compare normalized ISO strings lexicographically,
		//    which is correct for zero-padded ISO-8601.
		std::string now = normalize_iso(nowIso.empty() ? current_iso_datetime() : nowIso);
		if (!m_validFrom.empty())
		{
			if (now < normalize_iso(m_validFrom))
				return VerificationResult::notYetValid;
		}
		if (!m_validUntil.empty())
		{
			if (now > normalize_iso(m_validUntil))
				return VerificationResult::expired;
		}

		return VerificationResult::valid;
	}

	std::string License::toString(VerificationResult result)
	{
		switch (result)
		{
			case VerificationResult::valid:            return "valid";
			case VerificationResult::invalidSignature: return "invalid signature";
			case VerificationResult::wrongMachine:     return "wrong machine";
			case VerificationResult::notYetValid:      return "not yet valid";
			case VerificationResult::expired:          return "expired";
			case VerificationResult::clockTampering:   return "clock tampering";
			case VerificationResult::malformed:        return "malformed";
		}
		return "unknown";
	}

	std::string License::deriveSecret(const std::string& publicKey, const std::string& context) const
	{
		if (!isVerified(publicKey))
			return std::string();
		// The signature is unforgeable without the private key, so hashing it with
		// the caller's context yields a value an attacker cannot reproduce merely
		// by bypassing the verification branch.
		return sha256_hex(m_signature + "\x1e" + context);
	}

	bool License::signLicense(const std::string& privateKey)
	{
		EVP_PKEY* privKey = load_private_key_from_string(privateKey);
		if(!privKey)
			return false;
		m_signature = sign_message(privKey, getDataString());
		EVP_PKEY_free(privKey);
		return !m_signature.empty();
	}
	bool License::signLicenseFromFile(const std::string& privateKeyFile)
	{
		std::string privateKey;
		if(loadPrivateKeyFromFile(privateKeyFile, privateKey))
		{
			return signLicense(privateKey);
		}
		return false;
	}
	std::string License::generatePrivateKey()
	{
		EVP_PKEY* keypair = generate_RSA_keypair();
		if (!keypair)
			return std::string();
		std::string privateKeyPEM = private_key_to_string(keypair);
		EVP_PKEY_free(keypair);
		return privateKeyPEM;
	}
	std::string License::getPublicKeyFromPrivateKey(const std::string& privateKeyPEM)
	{
		EVP_PKEY* privateKey = load_private_key_from_string(privateKeyPEM);
		if (!privateKey)
			return std::string();
		// An EVP private key already carries the public components, so it can be
		// written directly as a SubjectPublicKeyInfo PEM.
		std::string publicKeyPEM = public_key_to_string(privateKey);
		EVP_PKEY_free(privateKey);
		return publicKeyPEM;
	}
	std::string License::signMessage(const std::string& privateKey, const std::string& message)
	{
		EVP_PKEY* pkey = load_private_key_from_string(privateKey);
		if (!pkey)
			return std::string();
		std::string signature = sign_message(pkey, message);
		EVP_PKEY_free(pkey);
		return signature;
	}

	bool License::savePublicKeyToFile(const std::string& publicKey, const std::string& filename)
	{
		return writeToFile(filename, publicKey);
	}
	bool License::savePrivateKeyToFile(const std::string& privateKey, const std::string& filename)
	{
		return writeToFile(filename, privateKey);
	}
	bool License::loadPublicKeyFromFile(const std::string& filename, std::string& publicKey)
	{
		return readFromFile(filename, publicKey);
	}
	bool License::loadPrivateKeyFromFile(const std::string& filename, std::string& privateKey)
	{
		return readFromFile(filename, privateKey);
	}
	bool License::writeToFile(const std::string& filename, const std::string& data)
	{
		QFile file(filename.c_str());
		if (file.open(QIODevice::WriteOnly))
		{
			QByteArray arr(data.c_str(), data.length());
			file.write(arr);
			file.close();
			return true;
		}
		Logger::logError(decryptedStrings().messages.errReadingFromFile + filename);
		return false;
	}
	bool License::readFromFile(const std::string& filename, std::string& data)
	{
		QFile file(filename.c_str());
		if (file.open(QIODevice::ReadOnly))
		{
			QByteArray arr = file.readAll();
			data = arr.toStdString();
			file.close();
			return true;
		}
		Logger::logError(decryptedStrings().messages.errReadingFromFile + filename);
		return false;
	}


	std::string License::getDataString() const
	{
		// Canonical, deterministic representation of everything that must be
		// tamper-protected. QJsonObject serializes its keys in sorted order and
		// Compact output has no insignificant whitespace, so the same license
		// always produces the same bytes to sign/verify.
		//
		// NOTE: this now covers the name, node-lock fingerprint and validity
		// window in addition to the license data. Licenses signed by older
		// versions of the library (which signed only the license data, indented)
		// will therefore no longer verify and must be re-issued.
		QJsonObject licenseData;
		for(auto it = m_licenseData.begin(); it != m_licenseData.end(); ++it)
		{
			licenseData[it->first.c_str()] = it->second.c_str();
		}

		QJsonObject payload;
		payload["schema"]     = 2;
		payload["licenseData"] = licenseData;
		payload["name"]       = m_name.c_str();
		payload["hardwareId"] = m_hardwareId.c_str();
		payload["validFrom"]  = m_validFrom.c_str();
		payload["validUntil"] = m_validUntil.c_str();

		QJsonDocument doc(payload);
		QByteArray data = doc.toJson(QJsonDocument::Compact);
		return data.toStdString();
	}


	void print_openssl_error()
	{
		// ERR_error_string requires a buffer of at least 256 bytes; the previous
		// 130-byte allocation could be overrun by OpenSSL.
		char err[256] = {0};
		ERR_error_string_n(ERR_get_error(), err, sizeof(err));
		Logger::logError(License::decryptedStrings().messages.errOpenSSL + std::string(err));
	}

	// Generate a 2048-bit RSA key pair via the modern EVP interface.
	EVP_PKEY* generate_RSA_keypair()
	{
		EVP_PKEY* pkey = EVP_RSA_gen(2048);
		if (!pkey)
		{
			Logger::logError(License::decryptedStrings().messages.errGettingRSAKeypair);
			print_openssl_error();
		}
		return pkey;
	}

	// Convert a private key to a PEM string (PKCS#8 "BEGIN PRIVATE KEY").
	std::string private_key_to_string(EVP_PKEY* private_key)
	{
		BIO* bio = BIO_new(BIO_s_mem());
		if (!bio)
			return "";
		if (!PEM_write_bio_PrivateKey(bio, private_key, NULL, NULL, 0, NULL, NULL))
		{
			Logger::logError(License::decryptedStrings().messages.errConvPrivToStr);
			print_openssl_error();
			BIO_free(bio);
			return "";
		}

		char* key_data = NULL;
		long key_length = BIO_get_mem_data(bio, &key_data);
		std::string private_key_str(key_data, key_length);

		BIO_free(bio);
		return private_key_str;
	}

	// Convert a key's public part to a PEM string (SubjectPublicKeyInfo,
	// "BEGIN PUBLIC KEY") — same format as previous library versions.
	std::string public_key_to_string(EVP_PKEY* key)
	{
		BIO* bio = BIO_new(BIO_s_mem());
		if (!bio)
			return "";
		if (!PEM_write_bio_PUBKEY(bio, key))
		{
			Logger::logError(License::decryptedStrings().messages.errConvPubToStr);
			print_openssl_error();
			BIO_free(bio);
			return "";
		}

		char* key_data = NULL;
		long key_length = BIO_get_mem_data(bio, &key_data);
		std::string public_key_str(key_data, key_length);

		BIO_free(bio);
		return public_key_str;
	}

	// Load a private key from a PEM string. Accepts both the traditional RSA PEM
	// written by older library versions and PKCS#8.
	EVP_PKEY* load_private_key_from_string(const std::string& private_key_str)
	{
		BIO* bio = BIO_new_mem_buf((const void*)private_key_str.data(), (int)private_key_str.size());
		if (!bio)
			return nullptr;
		EVP_PKEY* pkey = PEM_read_bio_PrivateKey(bio, NULL, NULL, NULL);
		if (!pkey)
		{
			Logger::logError(License::decryptedStrings().messages.errLoadPriv);
			print_openssl_error();
		}
		BIO_free(bio);
		return pkey;
	}

	// Load a public key from a SubjectPublicKeyInfo PEM string.
	EVP_PKEY* load_public_key_from_string(const std::string& public_key_str)
	{
		BIO* bio = BIO_new_mem_buf((const void*)public_key_str.data(), (int)public_key_str.size());
		if (!bio)
			return nullptr;
		EVP_PKEY* pkey = PEM_read_bio_PUBKEY(bio, NULL, NULL, NULL);
		if (!pkey)
		{
			Logger::logError(License::decryptedStrings().messages.errLoadPub);
			print_openssl_error();
		}
		BIO_free(bio);
		return pkey;
	}

	// Sign a message: PKCS#1 v1.5 over SHA-256, base64-encoded. Byte-compatible
	// with the previous RSA_sign(NID_sha256, ...) implementation.
	std::string sign_message(EVP_PKEY* private_key, const std::string& message)
	{
		if (!private_key)
			return "";

		EVP_MD_CTX* ctx = EVP_MD_CTX_new();
		if (!ctx)
			return "";

		std::string result;
		size_t sig_len = 0;
		if (EVP_DigestSignInit(ctx, NULL, EVP_sha256(), NULL, private_key) == 1 &&
			EVP_DigestSign(ctx, NULL, &sig_len, (const unsigned char*)message.data(), message.size()) == 1)
		{
			std::string signature(sig_len, '\0');
			if (EVP_DigestSign(ctx, (unsigned char*)signature.data(), &sig_len,
							   (const unsigned char*)message.data(), message.size()) == 1)
			{
				signature.resize(sig_len);
				result = signature_to_string(signature);
			}
			else
			{
				Logger::logError(License::decryptedStrings().messages.errSign);
				print_openssl_error();
			}
		}
		else
		{
			Logger::logError(License::decryptedStrings().messages.errSign);
			print_openssl_error();
		}

		EVP_MD_CTX_free(ctx);
		return result;
	}

	// Verify a base64 PKCS#1 v1.5 SHA-256 signature.
	bool verify_signature(EVP_PKEY* public_key, const std::string& message, const std::string& signature)
	{
		if (!public_key)
			return false;

		std::string raw = string_to_signature(signature);

		EVP_MD_CTX* ctx = EVP_MD_CTX_new();
		if (!ctx)
			return false;

		bool ok = false;
		if (EVP_DigestVerifyInit(ctx, NULL, EVP_sha256(), NULL, public_key) == 1)
		{
			int rc = EVP_DigestVerify(ctx, (const unsigned char*)raw.data(), raw.size(),
									  (const unsigned char*)message.data(), message.size());
			ok = (rc == 1);
		}

		if (!ok)
		{
			Logger::logError(License::decryptedStrings().messages.errSigVerFail);
			print_openssl_error();
		}

		EVP_MD_CTX_free(ctx);
		return ok;
	}
	// Encode binary data to Base64
	std::string base64_encode(const std::string& binary_data) 
	{
		BIO* bio = BIO_new(BIO_s_mem());
		BIO* b64 = BIO_new(BIO_f_base64());
		bio = BIO_push(b64, bio);
		BIO_write(bio, binary_data.data(), binary_data.size());
		BIO_flush(bio);

		BUF_MEM* buffer_ptr;
		BIO_get_mem_ptr(bio, &buffer_ptr);

		std::string base64_encoded(buffer_ptr->data, buffer_ptr->length);
		BIO_free_all(bio);

		return base64_encoded;
	}

	// Decode Base64 to binary data
	std::string base64_decode(const std::string& base64_data) 
	{
		BIO* bio = BIO_new_mem_buf(base64_data.data(), base64_data.size());
		BIO* b64 = BIO_new(BIO_f_base64());
		bio = BIO_push(b64, bio);

		std::vector<char> buffer(base64_data.size());
		int length = BIO_read(bio, buffer.data(), buffer.size());
		BIO_free_all(bio);

		return std::string(buffer.data(), length);
	}

	// Function to convert signature to Base64-encoded string
	std::string signature_to_string(const std::string& signature) 
	{
		return base64_encode(signature);
	}

	// Function to convert Base64-encoded string back to signature
	std::string string_to_signature(const std::string& base64_signature)
	{
		return base64_decode(base64_signature);
	}

	// SHA-256 of data as a lowercase hex string.
	std::string sha256_hex(const std::string& data)
	{
		unsigned char digest[EVP_MAX_MD_SIZE];
		unsigned int digestLen = 0;

		EVP_MD_CTX* ctx = EVP_MD_CTX_new();
		if (!ctx)
			return "";

		std::string out;
		if (EVP_DigestInit_ex(ctx, EVP_sha256(), NULL) == 1 &&
			EVP_DigestUpdate(ctx, data.data(), data.size()) == 1 &&
			EVP_DigestFinal_ex(ctx, digest, &digestLen) == 1)
		{
			static const char* hex = "0123456789abcdef";
			out.reserve(digestLen * 2);
			for (unsigned int i = 0; i < digestLen; ++i)
			{
				out.push_back(hex[(digest[i] >> 4) & 0xF]);
				out.push_back(hex[digest[i] & 0xF]);
			}
		}
		EVP_MD_CTX_free(ctx);
		return out;
	}

	// Current UTC time as "YYYY-MM-DDTHH:MM:SS".
	std::string current_iso_datetime()
	{
		std::time_t t = std::time(nullptr);
		std::tm tmv{};
#ifdef _WIN32
		gmtime_s(&tmv, &t);
#else
		gmtime_r(&t, &tmv);
#endif
		char buf[32];
		std::snprintf(buf, sizeof(buf), "%04d-%02d-%02dT%02d:%02d:%02d",
					  tmv.tm_year + 1900, tmv.tm_mon + 1, tmv.tm_mday,
					  tmv.tm_hour, tmv.tm_min, tmv.tm_sec);
		return std::string(buf);
	}

	// Normalize an ISO-ish timestamp for lexicographic comparison. A bare date
	// ("YYYY-MM-DD") is padded to the start of that day, and a space separator is
	// treated like the 'T' separator. Zero-padded ISO-8601 sorts chronologically
	// as plain text, so string comparison is a correct ordering.
	std::string normalize_iso(const std::string& iso)
	{
		if (iso.empty())
			return iso;
		std::string s = iso;
		for (char& c : s)
			if (c == ' ')
				c = 'T';
		if (s.size() == 10)   // date only
			s += "T00:00:00";
		return s;
	}
}